spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
couchbase.connection-string=127.0.0.1
couchbase.username=Administrator
couchbase.password=password
couchbase.bucket=todos
couchbase.scope=app
couchbase.collection=todos
