spring.datasource.url=jdbc:oracle:thin:@//127.0.0.1:1521/FREEPDB1
spring.datasource.username=todo
spring.datasource.password=todo
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
