spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
hbase.zookeeper.quorum=127.0.0.1
hbase.zookeeper.property.clientPort=2181
hbase.table.name=todos
hbase.column.family=cf
