spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
tigergraph.base-url=http://127.0.0.1:14240
tigergraph.graph-name=todos_graph
tigergraph.vertex-type=Todo
tigergraph.auth-token=
